services:
  db:
    image: postgres
    hostname: localhost # (use actual IP or "db") for adminer "Server" field
    container_name: hydrate_postgres
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: hydrate_admin # adminer "Username" field
      POSTGRES_PASSWORD: secret_password # adminer "Password" field
      POSTGRES_DB: hydrate_db # adminer "Database" field
    ports:
      - 5432:5432

  adminer:
    image: adminer
    hostname: adminer
    container_name: hydrate_adminer
    # restart: always
    ports:
      - 8282:8080
